class Errors:
    NO_VACANCIES_UNDER_LICENCES = "NO_VACANCIES_UNDER_LICENCES"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    IMPOSSIBLE_DELETE_OWNER = "IMPOSSIBLE_DELETE_OWNER"
    USER_CAN_NOT_CHANGE_STATUS = "USER_CAN_NOT_CHANGE_STATUS_ON_THE_NEXT"
    APPEAL_IS_CLOSED = "APPEAL_IS_CLOSED"
