class Errors:
    CLIENT_HAS_NOT_FREE_VACANCIES = "CLIENT_HAS_NOT_FREE_VACANCIES"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    IMPOSSIBLE_DELETE_OWNER = "IMPOSSIBLE_DELETE_OWNER"
    USER_CAN_NOT_CHANGE_STATUS = "USER_CAN_NOT_CHANGE_STATUS_ON_THE_NEXT"
    APPEAL_IS_CLOSED = "APPEAL_IS_CLOSED"
    COMPANY_IS_EXIST = "COMPANY_IS_EXIST"

    USER_HAS_ANOTHER_LICENCE = "USER_HAS_ANOTHER_LICENCE"
    LICENCE_IS_FULL = "LICENCE_IS_FULL"
    CLIENT_HAS_THIS_LICENCE = "CLIENT_HAS_THIS_LICENCE"

    MODULE_IS_EXIST = "MODULE_IS_EXIST"
    SOFTWARE_IS_EXIST = "SOFTWARE_IS_EXIST"
    LICENCE_IS_EXIST = "LICENCE_IS_EXIST"

    MODULE_IS_NOT_EXIST = "MODULE_IS_NOT_EXIST"
    SOFTWARE_IS_NOT_EXIST = "SOFTWARE_IS_NOT_EXIST"
    LICENCE_IS_NOT_EXIST = "LICENCE_IS_NOT_EXIST"

    MODULE_FOR_THIS_SOFTWARE_IS_EXIST = "MODULE_FOR_THIS_SOFTWARE_IS_EXIST"
    MODULE_FOR_THIS_SOFTWARE_IS_NOT_EXIST = "MODULE_FOR_THIS_SOFTWARE_IS_NOT_EXIST"

    CLIENT_NOT_FOUND = "CLIENT_NOT_FOUND"
